theme: jekyll-theme-minimal
title: The Gerber Family Travel Blog
description: our adventures in Germany and environs


# Site Settings
locale                   : "en-US"
title                    : "Moomin and Gingy"
title_separator          : "-"
name                     : &name "The Gerber Family"
url                      : https://julianesgerber.github.io

