theme: jekyll-theme-minimal
title: The Gerber Family Travel Blog
description: our adventures in Germany and environs
logo: /assets/img/logo.png

# Site Settings
locale                   : "en-US"
title                    : "The adventures of M & G"
title_separator          : "-"
name                     : &name "The Gerber Family"
url                      : https://julianesgerber.github.io

